# Generated by Django 3.1.3 on 2021-01-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_product_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Classic', 'Classic'), ('Drama', 'Drama'), ('Сrime fiction', 'Crime fiction'), ('Horror', 'Horror')], max_length=200, null=True),
        ),
    ]
