# Generated by Django 3.1.3 on 2021-01-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210113_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Классика', 'Классика'), ('Драма', 'Драма'), ('Детектив', 'Детектив'), ('Ужасы', 'Ужасы')], max_length=200, null=True),
        ),
    ]
